name: CI

on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      SENDERS_EMAIL: ${{secrets.SENDERS_EMAIL}}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}


    steps:
    - name: check the code
      uses: actions/checkout@v4

    - name: set up og python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: installing all dependencies
      run: |
        pip install -r requirements.txt



    - name: running tests
      run: |
        pip install pytest
        pytest
