"""code column added

Revision ID: de310d53812b
Revises: 5d6d2aecc7ae
Create Date: 2026-02-19 14:24:57.638774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de310d53812b'
down_revision: Union[str, Sequence[str], None] = '5d6d2aecc7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('language', sa.String(), nullable=False))
    op.alter_column('snippets', 'code',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False))
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password')
    op.alter_column('snippets', 'code',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('snippets', 'language')
    # ### end Alembic commands ###
