name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    -   name: setting up secret key
        run: |
            echo "${{ secrets.EC2_KEY }}" > ~/codesnippet.pem
            chmod 400 ~/codesnippet.pem

    -   name: accesing ec2 and deploying on ec2
        run: |
          ssh -o StrictHostKeyChecking=no \-i ~/codesnippet.pem \ubuntu@${{ secrets.EC2_HOST }} << EOF
              cd /home/ubuntu/SnippetValut
              git pull origin main
              sudo docker compose down
              sudo docker compose build
              sudo docker compose up -d
          EOF
